package com.csis3275.BlackboxTests;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.junit.After;
import org.junit.Before;
//Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class EmployeeLeaveApplicationTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "c:/temp/chromedriver.exe");

		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void employeeLeaveApplication() {
		driver.get("http://localhost:8080/");
		driver.manage().window().setSize(new Dimension(834, 824));
		driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
		driver.findElement(By.id("username")).click();
		driver.findElement(By.id("username")).sendKeys("rita");
		driver.findElement(By.id("password")).click();
		driver.findElement(By.id("password")).sendKeys("ritapass");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".btn-outline-info")).click();
		driver.findElement(By.id("inputStartDate")).click();
		driver.findElement(By.id("inputStartDate")).sendKeys("2020-12-04");
		driver.findElement(By.id("inputEndDate")).click();
		driver.findElement(By.id("inputEndDate")).sendKeys("2020-12-05");
		driver.findElement(By.id("inputEndDate")).click();
		driver.findElement(By.id("inputEndDate")).sendKeys("2020-12-09");
		driver.findElement(By.id("inputHoliday")).click();
		driver.findElement(By.id("inputReason")).click();
		driver.findElement(By.id("inputReason")).sendKeys("Christmas");
		driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
		driver.findElement(By.cssSelector(".btn-sm")).click();
		driver.findElement(By.id("username")).sendKeys("admin");
		driver.findElement(By.id("password")).click();
		driver.findElement(By.id("password")).sendKeys("adminpass");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector("a > .btn")).click();
		
		assertThat(
				driver.findElement(By.cssSelector(".table:nth-child(7) tr:nth-child(1) > td:nth-child(2)")).getText(),
				is("3"));
		assertThat(
				driver.findElement(By.cssSelector(".table:nth-child(7) tr:nth-child(4) > td:nth-child(2)")).getText(),
				is("Christmas"));
		assertThat(
				driver.findElement(By.cssSelector(".table:nth-child(7) tr:nth-child(5) > td:nth-child(2)")).getText(),
				is("holidays"));
	}
}
