package com.csis3275.BlackboxTests;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class GenerateSalaryTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "c:/temp/chromedriver.exe");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void generateSalary() {
		driver.get("http://localhost:8080/");
		driver.manage().window().setSize(new Dimension(922, 824));
		driver.findElement(By.id("username")).click();
		driver.findElement(By.id("username")).sendKeys("admin");
		driver.findElement(By.id("password")).sendKeys("adminpass");
		driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
		assertThat(driver.findElement(By.xpath("/html/body/div[2]/table/tbody/tr[2]/td[1]")).getText(), is("2"));
		assertThat(driver.findElement(By.xpath("/html/body/div[2]/table/tbody/tr[3]/td[1]")).getText(), is("3"));
		assertThat(driver.findElement(By.xpath("/html/body/div[2]/table/tbody/tr[4]/td[1]")).getText(), is("4"));
		assertThat(driver.findElement(By.xpath("/html/body/div[2]/table/tbody/tr[5]/td[1]")).getText(), is("5"));
		assertThat(driver.findElement(By.xpath("/html/body/div[2]/table/tbody/tr[2]/td[2]")).getText(),
				is("2020-11-29 - 2020-12-13"));
		driver.findElement(By.cssSelector(".text-right > .btn")).click();
		driver.findElement(By.id("username")).click();
		driver.findElement(By.id("username")).sendKeys("tarek");
		driver.findElement(By.id("password")).sendKeys("tarekpass");
		driver.findElement(By.cssSelector(".btn")).click();
		assertThat(driver.findElement(By.xpath("/html/body/div[3]/table/tbody[1]/tr/td[2]")).getText(), is("1987.25"));
		driver.findElement(By.cssSelector(".btn-sm")).click();
		driver.findElement(By.id("username")).click();
		driver.findElement(By.id("username")).sendKeys("admin");
		driver.findElement(By.id("password")).sendKeys("adminpass");
		driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
		driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(3) > a")).click();
		driver.findElement(By.cssSelector(".btn-outline-primary")).click();
		driver.findElement(By.cssSelector(".text-right > .btn")).click();
		driver.findElement(By.id("username")).sendKeys("tarek");
		driver.findElement(By.id("password")).sendKeys("tarekpass");
		driver.findElement(By.cssSelector(".btn")).click();
		assertThat(driver.findElement(By.xpath("/html/body/div[3]/table/tbody[3]/tr/td[2]")).getText(), is("1467.255"));
	}
}
