INSERT INTO JOBS_MAVERICKS (TITLE,SALARY_PER_DAY,PAY_PERIOD) VALUES ('SOFTWARE ENGINEER I',250,10);
INSERT INTO JOBS_MAVERICKS (TITLE,SALARY_PER_DAY,PAY_PERIOD) VALUES ('SOFTWARE ENGINEER II',200,10);
INSERT INTO JOBS_MAVERICKS (TITLE,SALARY_PER_DAY,PAY_PERIOD) VALUES ('SOFTWARE ARCHITECT',200,10);
INSERT INTO JOBS_MAVERICKS (TITLE,SALARY_PER_DAY,PAY_PERIOD) VALUES ('SOFTWARE TESTER',150,10);


INSERT INTO USERS_MAVERICKS (USERNAME,EMAIL,FIRST_NAME,LAST_NAME,PHONE_NUMBER,PASSWORD,CONFIRM_PASSWORD,IS_ADMIN,JOB_ID) VALUES('admin','admin@gmail.com','Mr','Admin','123123123','adminpass','adminpass',TRUE,1);
INSERT INTO USERS_MAVERICKS (USERNAME,EMAIL,FIRST_NAME,LAST_NAME,PHONE_NUMBER,PASSWORD,CONFIRM_PASSWORD,IS_ADMIN,JOB_ID) VALUES('melanie','melanie@gmail.com','Melanie','kung','123123123','melaniepass','melaniepass',False,2);
INSERT INTO USERS_MAVERICKS (USERNAME,EMAIL,FIRST_NAME,LAST_NAME,PHONE_NUMBER,PASSWORD,CONFIRM_PASSWORD,IS_ADMIN,JOB_ID) VALUES('rita','rita@gmail.com','Rita','Ak','123123123','ritapass','ritapass',FALSE,2);
INSERT INTO USERS_MAVERICKS (USERNAME,EMAIL,FIRST_NAME,LAST_NAME,PHONE_NUMBER,PASSWORD,CONFIRM_PASSWORD,IS_ADMIN,JOB_ID) VALUES('tarek','tarek@gmail.com','Tarek','Ahmed','123123123','tarekpass','tarekpass',FALSE,2);